services:
  dao-metademocracia-front:
    image: metademocracia1/dao-metademocracia-front:latest
    container_name: dao-metademocracia-front
    restart: always
    ports:
      - "8000:80"  # Maps host port 8000 to container port 80
    networks:
      - app-network

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    restart: always
    ports:
      - "80:80"     # HTTP traffic (ADD THIS LINE)
      - "81:81"     # NPM admin panel
      - "443:443"   # HTTPS traffic
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app-network
    depends_on:
      - dao-metademocracia-front

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower-latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30

networks:
  app-network:
    driver: bridge